name: dbt-docs

on:
  push:

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  generate-dbt-docs:
    runs-on: ubuntu-latest
    name: generate dbt doc artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.11"

      - name: Install Python dependencies
        run: python3 -m pip install -r ./requirements.txt --user

      - name: generate docs
        run: dbt deps && dbt --profiles-dir . docs generate

      - name: save doc artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dbt-doc-artifacts
          path: |
            target/index.html
            target/catalog.json
            target/manifest.json  

  publish_dbt_docs:
    runs-on: ubuntu-latest
    name: Publish dbt docs
    needs: generate-dbt-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: gsutil auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCS_SA_KEY }}'

      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@v0

      - name: Archive existing dbt docs
        run: ./tools/bin/archive_current_dbt_docs.sh

      - name: Download dbt docs artifacts
        uses: actions/download-artifact@v3
        with:
          name: dbt-doc-artifacts

